# -*- coding: utf-8 -*-
"""HRA_Info_Vis (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uMe4CmFiM0g1zP1fFcDobhds8K_byiFh
"""

!pip -q install duckdb pyarrow pandas

import duckdb
import pandas as pd

"""# Define File Paths and Create Database Connection"""

PARQUET_PATH = "/content/2026-01-13_hra-logs.parquet"
DB_PATH = "/content/hra_usage.duckdb"

con = duckdb.connect(DB_PATH)

"""## Building Base View from Raw Parquet

In this step, we create a reusable base view from the raw parquet file.  
We also combine the separate `date` and `time` columns into a single `event_ts` timestamp field, which will later help with time-based aggregation and trend analysis.

"""

con.execute(f"""
CREATE OR REPLACE VIEW logs_base AS
SELECT
    anon_id,
    date,
    time,
    CAST(CAST(date AS VARCHAR) || ' ' || time AS TIMESTAMP) AS event_ts,
    x_edge_location,
    sc_bytes,
    cs_method,
    cs_uri_stem,
    sc_status,
    cs_referer,
    cs_user_agent,
    cs_uri_query,
    cs_cookie,
    x_edge_result_type,
    x_edge_request_id,
    x_host_header,
    cs_protocol,
    cs_bytes,
    time_taken,
    ssl_protocol,
    ssl_cipher,
    x_edge_response_result_type,
    cs_protocol_version,
    time_to_first_byte,
    x_edge_detailed_result_type,
    sc_content_type,
    sc_content_len,
    sc_range_start,
    sc_range_end,
    timestamp,
    timestamp_ms,
    c_country,
    query,
    traffic_type,
    referrer,
    airport,
    month,
    day,
    distribution,
    site,
    year
FROM read_parquet('{PARQUET_PATH}')
WHERE date IS NOT NULL
  AND time IS NOT NULL
""")

"""# Basic Dataset Validation"""

summary_df = con.execute("""
SELECT
    COUNT(*) AS total_rows,
    MIN(event_ts) AS min_ts,
    MAX(event_ts) AS max_ts,
    COUNT(DISTINCT anon_id) AS unique_users,
    COUNT(DISTINCT cs_uri_stem) AS unique_paths,
    COUNT(DISTINCT c_country) AS unique_countries
FROM logs_base
""").df()

display(summary_df)

"""## Create Clean Working Table

Here, we build a cleaned version of the raw logs that keeps only the columns needed for analysis.  
We also standardize path and referrer fields and derive day, week, and month timestamp buckets for later aggregation.

"""

con.execute("""
CREATE OR REPLACE TABLE logs_clean AS
SELECT
    anon_id,
    event_ts,
    DATE_TRUNC('day', event_ts) AS event_day,
    DATE_TRUNC('week', event_ts) AS event_week,
    DATE_TRUNC('month', event_ts) AS event_month,
    LOWER(TRIM(cs_uri_stem)) AS path,
    LOWER(TRIM(cs_uri_query)) AS raw_query_string,
    sc_status,
    c_country,
    traffic_type,
    LOWER(TRIM(referrer)) AS referrer,
    LOWER(TRIM(cs_referer)) AS cs_referer,
    query,
    distribution,
    site
FROM logs_base
WHERE anon_id IS NOT NULL
  AND event_ts IS NOT NULL
  AND cs_uri_stem IS NOT NULL
""")

"""## Data Quality Check

This section performs a quick sanity check on the cleaned table.  
We verify how many rows remain after cleaning, how many unique users are present, and how many distinct paths exist. This helps confirm that the cleaning process did not accidentally remove too much data.
"""

data_quality_check_df = con.execute("""
SELECT
    COUNT(*) AS rows_after_cleaning,
    COUNT(DISTINCT anon_id) AS unique_users,
    COUNT(DISTINCT path) AS unique_paths
FROM logs_clean
""").df()

display(data_quality_check_df)

"""## Explore Most Frequent Paths

At this stage, we inspect the most requested paths in the cleaned dataset.  
This gives us an initial sense of what kinds of endpoints dominate the traffic and helps us understand how HRA interfaces and APIs appear in the logs.

"""

top_paths_df = con.execute("""
SELECT
    path,
    COUNT(*) AS hits
FROM logs_clean
GROUP BY 1
ORDER BY hits DESC
LIMIT 100
""").df()

display(top_paths_df)

"""## Initial Interface Mapping Attempt

This section represents an early pass at assigning requests to RUI, EUI, CDE, and OTHER.  
It was useful for initial exploration, but the mapping is refined later in the notebook after filtering static assets and inspecting API/UI path families more carefully.

"""

con.execute("""
CREATE OR REPLACE VIEW logs_labeled AS
SELECT
    *,
    CASE
        -- EUI
        WHEN path LIKE '/ui/ccf-eui%' THEN 'EUI'
        WHEN path LIKE '%reference-organ%' THEN 'EUI'
        WHEN path LIKE '%scene%' THEN 'EUI'

        -- RUI
        WHEN path LIKE '%tissue-block%' THEN 'RUI'
        WHEN path LIKE '%collision%' THEN 'RUI'

        -- CDE
        WHEN path LIKE '%cell-distance%' THEN 'CDE'
        WHEN path LIKE '%histogram%' THEN 'CDE'
        WHEN path LIKE '%violin%' THEN 'CDE'

        ELSE 'OTHER'
    END AS interface_guess
FROM logs_clean
""")

interface_summary_df = con.execute("""
SELECT
    interface_guess,
    COUNT(*) AS events,
    COUNT(DISTINCT anon_id) AS users
FROM logs_labeled
GROUP BY 1
ORDER BY events DESC
""").df()

display(interface_summary_df)

con.execute("""
CREATE OR REPLACE TABLE monthly_usage AS
SELECT
    event_month,
    interface_guess,
    COUNT(*) AS event_count,
    COUNT(DISTINCT anon_id) AS unique_users
FROM logs_labeled
WHERE event_month >= DATE '2023-10-01'
  AND event_month < DATE '2026-04-01'
GROUP BY 1, 2
ORDER BY 1, 2
""")

monthly_usage_df = con.execute("""
SELECT *
FROM monthly_usage
ORDER BY event_month, interface_guess
""").df()

display(monthly_usage_df.head(30))

top_paths_by_interface_df = con.execute("""
SELECT
    interface_guess,
    path,
    COUNT(*) AS hits
FROM logs_labeled
WHERE interface_guess <> 'OTHER'
GROUP BY 1, 2
ORDER BY interface_guess, hits DESC
""").df()

display(top_paths_by_interface_df.head(50))

"""## Remove Static Asset Traffic

Not all requests represent meaningful feature usage.  
In this section, we remove obvious static asset requests such as CSS, JavaScript, images, and fonts so the remaining data is more useful for behavioral analysis.

"""

con.execute("""
CREATE OR REPLACE TABLE logs_actions AS
SELECT *
FROM logs_clean
WHERE path NOT LIKE '%.css'
  AND path NOT LIKE '%.js'
  AND path NOT LIKE '%.svg'
  AND path NOT LIKE '%.png'
  AND path NOT LIKE '%.jpg'
  AND path NOT LIKE '%.jpeg'
  AND path NOT LIKE '%.gif'
  AND path NOT LIKE '%.woff'
  AND path NOT LIKE '%.woff2'
  AND path NOT LIKE '%.ttf'
  AND path NOT LIKE '%.ico'
""")

"""## Inspect Action-Oriented Paths

After filtering out static resources, we inspect the remaining high-frequency paths.  
This gives us a better view of actual content, API, and interaction-related requests that may correspond to user behavior.

"""

action_paths_df = con.execute("""
SELECT
    path,
    COUNT(*) AS hits
FROM logs_actions
GROUP BY 1
ORDER BY hits DESC
LIMIT 200
""").df()

display(action_paths_df)

"""## Remove Root Path for Feature Analysis

The root path `/` is useful for general traffic analysis, but it is not helpful for understanding specific feature usage.  
We remove it here so the later feature-level results are easier to interpret.

"""

con.execute("""
CREATE OR REPLACE TABLE logs_actions_no_root AS
SELECT *
FROM logs_actions
WHERE path <> '/'
""")

"""## Inspect API Endpoints

This section isolates API-related paths from the filtered dataset.  
The goal is to understand which backend endpoints are most frequently used and to identify endpoint families that may correspond to RUI, EUI, or CDE workflows.

"""

api_paths_df = con.execute("""
SELECT
    path,
    COUNT(*) AS hits
FROM logs_actions_no_root
WHERE path LIKE '/api/%'
   OR path LIKE '/hra-api%'
   OR path LIKE '/hubmap-hra-api%'
GROUP BY 1
ORDER BY hits DESC
LIMIT 200
""").df()

display(api_paths_df)

"""## Inspect UI Routes

Here, we examine frontend interface routes under `/ui/`.  
These paths are especially useful for identifying which requests belong to EUI, RUI, and CDE, and they help improve the interface-mapping logic.

"""

ui_paths_df = con.execute("""
SELECT
    path,
    COUNT(*) AS hits
FROM logs_actions_no_root
WHERE path LIKE '/ui/%'
GROUP BY 1
ORDER BY hits DESC
LIMIT 200
""").df()

display(ui_paths_df)

"""## Refined Interface Mapping

Using the patterns observed in the API and UI path exploration steps, we now rebuild the interface mapping.  
Each request is assigned to one of the target interfaces: RUI, EUI, CDE, or OTHER. This refined version is more reliable than the earlier exploratory pass.

"""

con.execute("""
CREATE OR REPLACE VIEW logs_labeled AS
SELECT
    *,
    CASE
        -- Frontend UI routes
        WHEN path LIKE '/ui/ccf-eui%' THEN 'EUI'
        WHEN path LIKE '/ui/ccf-rui%' THEN 'RUI'
        WHEN path LIKE '/ui/cde-ui%' THEN 'CDE'
        WHEN path LIKE '/ui/ftu-ui%' THEN 'OTHER'

        -- RUI-related API endpoints
        WHEN path LIKE '%collision%' THEN 'RUI'
        WHEN path LIKE '%tissue-block%' THEN 'RUI'
        WHEN path LIKE '%get-spatial-placement%' THEN 'RUI'
        WHEN path LIKE '%extraction-site%' THEN 'RUI'
        WHEN path LIKE '%rui_locations%' THEN 'RUI'

        -- EUI-related API/content endpoints
        WHEN path LIKE '%reference-organ%' THEN 'EUI'
        WHEN path LIKE '%scene%' THEN 'EUI'
        WHEN path LIKE '%ontology%' THEN 'EUI'
        WHEN path LIKE '%cell-type%' THEN 'EUI'
        WHEN path LIKE '%biomarker%' THEN 'EUI'
        WHEN path LIKE '%provider-names%' THEN 'EUI'
        WHEN path LIKE '%technology-names%' THEN 'EUI'
        WHEN path LIKE '%aggregate-results%' THEN 'EUI'
        WHEN path LIKE '%ontology-tree-model%' THEN 'EUI'
        WHEN path LIKE '%cell-type-tree-model%' THEN 'EUI'

        -- CDE-related API/content endpoints
        WHEN path LIKE '%cde%' THEN 'CDE'
        WHEN path LIKE '%cell-distance%' THEN 'CDE'
        WHEN path LIKE '%histogram%' THEN 'CDE'
        WHEN path LIKE '%violin%' THEN 'CDE'

        ELSE 'OTHER'
    END AS interface_guess
FROM logs_actions_no_root
""")

"""> **Note:** Interface labels in this notebook are inferred from path patterns and endpoint families observed in the logs.  
> They are useful for analysis, but they should be interpreted as heuristic mappings rather than perfect ground-truth labels.

"""

interface_summary_df = con.execute("""
SELECT
    interface_guess,
    COUNT(*) AS events,
    COUNT(DISTINCT anon_id) AS users
FROM logs_labeled
GROUP BY 1
ORDER BY events DESC
""").df()

display(interface_summary_df)

"""## Inspect Top Paths by Interface

Here, we review the most frequent paths within each mapped interface.  
This helps validate the quality of the refined mapping and gives a first look at the kinds of requests associated with RUI, EUI, and CDE.

"""

top_paths_by_interface_df = con.execute("""
SELECT
    interface_guess,
    path,
    COUNT(*) AS hits
FROM logs_labeled
WHERE interface_guess <> 'OTHER'
GROUP BY 1, 2
ORDER BY interface_guess, hits DESC
""").df()

display(top_paths_by_interface_df.head(100))

"""## Initial Summary Tables from Refined Interface Mapping

At this stage, we build summary tables directly from the refined interface-labeled data.  
These tables are useful for early validation, but the feature and trend summaries are further cleaned later by removing remaining non-feature resource requests.

"""

con.execute("""
CREATE OR REPLACE TABLE monthly_usage AS
SELECT
    event_month,
    interface_guess,
    COUNT(*) AS event_count,
    COUNT(DISTINCT anon_id) AS unique_users
FROM logs_labeled
WHERE event_month >= DATE '2023-10-01'
  AND event_month < DATE '2026-04-01'
GROUP BY 1, 2
ORDER BY 1, 2
""")

monthly_usage_df = con.execute("""
SELECT *
FROM monthly_usage
ORDER BY event_month, interface_guess
""").df()

display(monthly_usage_df.head(50))

con.execute("""
CREATE OR REPLACE TABLE feature_frequency AS
SELECT
    interface_guess,
    path AS feature_proxy,
    COUNT(*) AS event_count,
    COUNT(DISTINCT anon_id) AS unique_users
FROM logs_labeled
GROUP BY 1, 2
ORDER BY event_count DESC
""")

top_features_df = con.execute("""
SELECT *
FROM feature_frequency
WHERE interface_guess <> 'OTHER'
ORDER BY event_count DESC
LIMIT 50
""").df()

display(top_features_df)

con.execute("""
CREATE OR REPLACE TABLE traffic_summary AS
SELECT
    traffic_type,
    COUNT(*) AS events,
    COUNT(DISTINCT anon_id) AS users
FROM logs_labeled
GROUP BY 1
ORDER BY events DESC
""")

con.execute("""
CREATE OR REPLACE TABLE geography_summary AS
SELECT
    c_country,
    COUNT(*) AS events,
    COUNT(DISTINCT anon_id) AS users
FROM logs_labeled
GROUP BY 1
ORDER BY events DESC
""")

"""## Create Feature-Focused Action Table

Even after removing static assets, some requests still reflect background resources rather than meaningful feature usage.  
In this section, we create a stricter filtered table intended for feature analysis by excluding additional resource files and system-level endpoints.

"""

con.execute("""
CREATE OR REPLACE TABLE logs_feature_actions AS
SELECT *
FROM logs_labeled
WHERE path NOT LIKE '%/assets/%'
  AND path NOT LIKE '%.json'
  AND path NOT LIKE '%.jsonld'
  AND path NOT LIKE '%.yml'
  AND path NOT LIKE '%db-status%'
  AND path NOT LIKE '%config.env%'
  AND path NOT LIKE '/api'
""")

"""## Compute Feature Frequency

This table summarizes how often each endpoint-like feature proxy appears in the filtered dataset.  
Because the logs are request-based, these results should be interpreted as feature-related endpoint usage rather than exact user click counts.

"""

con.execute("""
CREATE OR REPLACE TABLE feature_frequency AS
SELECT
    interface_guess,
    path AS feature_proxy,
    COUNT(*) AS event_count,
    COUNT(DISTINCT anon_id) AS unique_users
FROM logs_feature_actions
GROUP BY 1, 2
ORDER BY event_count DESC
""")

"""> **Note:** The feature frequency results are based on endpoint-level request patterns.  
> They should be interpreted as feature-related usage proxies, not exact clickstream actions.

"""

top_features_df = con.execute("""
SELECT *
FROM feature_frequency
WHERE interface_guess <> 'OTHER'
ORDER BY event_count DESC
LIMIT 50
""").df()

display(top_features_df)

"""## Inspect Top and Least Used Features

In this section, we identify the most frequently used and least frequently used feature proxies across interfaces.  
This supports the project goal of understanding which parts of the Human Atlas system are heavily used and which are rarely accessed.

"""

least_features_df = con.execute("""
SELECT *
FROM feature_frequency
WHERE interface_guess <> 'OTHER'
  AND event_count >= 5
ORDER BY event_count ASC
LIMIT 50
""").df()

display(least_features_df)

"""## Build Monthly Usage Table

Here, we aggregate usage by month and interface using the stricter feature-focused dataset.  
This table supports temporal trend analysis and helps compare how activity changes over time across RUI, EUI, and CDE.

"""

con.execute("""
CREATE OR REPLACE TABLE monthly_usage AS
SELECT
    event_month,
    interface_guess,
    COUNT(*) AS event_count,
    COUNT(DISTINCT anon_id) AS unique_users
FROM logs_feature_actions
WHERE event_month >= DATE '2023-10-01'
  AND event_month < DATE '2026-04-01'
GROUP BY 1, 2
ORDER BY 1, 2
""")

"""## Preview Monthly Usage Trends

This step displays the monthly aggregated usage table so we can quickly verify that the trend data looks correct before exporting it for visualization and reporting.

"""

monthly_usage_df = con.execute("""
SELECT *
FROM monthly_usage
ORDER BY event_month, interface_guess
""").df()

display(monthly_usage_df.head(50))

"""## Summarize Traffic Type

This section groups requests by `traffic_type` to compare human and bot activity.  
It supports the project’s bot-vs-human analysis and helps us understand what proportion of total traffic likely comes from real users.

"""

traffic_summary_df = con.execute("""
SELECT
    traffic_type,
    COUNT(*) AS events,
    COUNT(DISTINCT anon_id) AS users
FROM logs_labeled
GROUP BY 1
ORDER BY events DESC
""").df()

display(traffic_summary_df)

"""## Summarize Geographic Distribution

Here, we aggregate usage by country using the `c_country` field.  
This helps answer the geography-related project question by showing which countries generate the most activity in the dataset.

"""

geography_summary_df = con.execute("""
SELECT
    c_country,
    COUNT(*) AS events,
    COUNT(DISTINCT anon_id) AS users
FROM logs_labeled
GROUP BY 1
ORDER BY events DESC
LIMIT 50
""").df()

display(geography_summary_df)

"""## Export Final Tables

In this step, we export the cleaned summary tables as CSV files.

"""

con.execute("COPY monthly_usage TO '/content/monthly_usage.csv' (HEADER, DELIMITER ',')")
con.execute("COPY feature_frequency TO '/content/feature_frequency.csv' (HEADER, DELIMITER ',')")
con.execute("COPY traffic_summary TO '/content/traffic_summary.csv' (HEADER, DELIMITER ',')")
con.execute("COPY geography_summary TO '/content/geography_summary.csv' (HEADER, DELIMITER ',')")